### PR TITLE
Added support for any() function as described. Fully tested and ...

### PR DESCRIPTION
**Pull request by jmcdo29**
updated the readme.

### CODE REVIEW

**Comment by joeltankam** [comment]
Thanks for your pull request :heart_eyes: 
I'll check it out as soon as possible

**Comment by joeltankam** [comment]
Can you please fix [issues returned by Codacy ](https://app.codacy.com/app/ifjs/if.js/pullRequest?prid=2281213) ?

**Comment by jmcdo29** [comment]
Sure. Will do.

**Comment by jmcdo29** [comment]
There we are! All issues fixed

**Comment by joeltankam** [comment]
Closed by #13 
Thank you very much for your contribution

**Pull request closed without merging**
